version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.4.6
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Asia/Kolkata"
      TZ: "Asia/Kolkata"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_MODE: "external"
      N8N_RUNNERS_AUTH_TOKEN: "${N8N_RUNNERS_AUTH_TOKEN}"
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: "0.0.0.0"
      N8N_RUNNERS_BROKER_PORT: "5679"
      N8N_RUNNERS_STDLIB_ALLOW: "*"
      N8N_RUNNERS_EXTERNAL_ALLOW: "*"
      # Use Portainer environment variables for your domain for easier management
      WEBHOOK_URL: "https://${DOMAIN}" 
    volumes:
      - n8n_data:/home/node/.n8n

  runners:
    build:
      context: ./runners
    container_name: n8n-runners
    restart: unless-stopped
    environment:
      N8N_RUNNERS_AUTH_TOKEN: "${N8N_RUNNERS_AUTH_TOKEN}"
      N8N_RUNNERS_TASK_BROKER_URI: "http://n8n:5679"
      N8N_RUNNERS_STDLIB_ALLOW: "*"
      N8N_RUNNERS_EXTERNAL_ALLOW: "*"
    volumes:
      - ./config/n8n-task-runners.json:/etc/n8n-task-runners.json
    depends_on:
      - n8n

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflaretunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARE_TOKEN}"

volumes:
  n8n_data:
